repos:
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
    -   id: autopep8
        files: ^backend/

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
        files: ^backend/
    -   id: end-of-file-fixer
        files: ^backend/
    -   id: trailing-whitespace
        files: ^backend/
    -   id: check-added-large-files
        files: ^backend/
