# Generated by Django 3.2 on 2023-04-02 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0008_auto_20230402_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': (
                '-pub_date',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now,
                                       verbose_name='Дата публикации'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(
                fields=('name', 'author'), name='unique_name_author_recip'),
        ),
    ]
