# Generated by Django 3.2 on 2023-04-03 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[
                                   django.core.validators.RegexValidator('^[\\w.@+-]+\\z')], verbose_name='Username'),
        ),
    ]
